### ISSUE TITLE
Essential won't work in hexxit 1.6.0

### ISSUE THREAD

**Issue by n18rt** [xJon/Hexxit-II#252]
### Was this help requested before?

- [x] No, it was not.

### Please describe what you need help with

What is the mods that i need to delete to make essential work

**Comment by xJon** [comment]
Can you share your game log? It might give a hint, I'm not sure. Also make sure you're using the latest version of the Essential mod.

**Comment by n18rt** [comment]
[crash-2025-03-28_05.10.28-client.txt](https://github.com/user-attachments/files/19497494/crash-2025-03-28_05.10.28-client.txt)

**Comment by n18rt** [comment]
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// There are four lights!

Time: 2025-03-28 05:10:28 AST
Description: Initializing game

java.lang.NoSuchMethodError: kotlinx.coroutines.channels.ChannelKt.Channel$default(ILkotlinx/coroutines/channels/BufferOverflow;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lkotlinx/coroutines/channels/Channel;
    at gg.essential.network.connectionmanager.ConnectionManagerKt.<init>(ConnectionManagerKt.kt:76)
    at gg.essential.network.connectionmanager.ConnectionManager.<init>(ConnectionManager.java:162)
    at gg.essential.Essential.<init>(Essential.java:132)
    at gg.essential.Essential.getInstance(Essential.java:162)
    at gg.essential.mixins.impl.client.MinecraftHook.preinit(MinecraftHook.java:39)
    at net.minecraft.client.Minecraft.handler$bcj000$preinit(MinecraftMixin.java:11603)
    at net.minecraft.client.Minecraft.init(MinecraftMixin.java)
    at net.minecraft.client.Minecraft.run(MinecraftMixin.java:5601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

No Mixin Metadata is found in the Stacktrace.


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 9134369792 bytes (8711 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms10240m -Xmx10240m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: 
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.6-185-technic.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      WolfArmorCore (WolfArmorAndStorage-3.8.1+1.12.2.alpha.1-SNAPSHOT-signed.jar)
                                        
                                      ReachFixPlugin (ReachFix-1.12.2-1.1.1.jar)
                                        meldexun.reachfix.asm.ReachFixClassTransformer
                                      LoliASM (censoredasm5.26.jar)
                                        
                                      ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
                                        wanion.unidict.core.UniDictCoreModTransformer
                                      PhosphorFMLPlugin (phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar)
                                        
                                      ZenUtilsPlugin (zenutils-1.21.8.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      MSLoadingPlugin (modernsplash-1.12.2-1.3.1.jar)
                                        
                                      ChunkGenLimiterCoremod (chunkgenlimiter-1.1-core.jar)
                                        io.github.barteks2x.chunkgenlimiter.coremod.ChunkGenLimitTransformer
                                      CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.7.0B-hex.jar)
                                        team.cqr.cqrepoured.asm.CQRClassTransformer
                                      JEIAreaFixerEarlyMixin (jei_area_fixer-2.0.0.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.4.3.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      RenderLibPlugin (RenderLib-1.12.2-1.4.1.jar)
                                        
                                      MixinLoader (LootTweaker-0.4.1+MC1.12.2.jar)
                                        
                                      Naughthirium (naughthirium-2.2.1.jar)
                                        
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Aqua Acrobatics Transformer (AquaAcrobatics-1.15.4.jar)
                                        
                                      FluxLoading Core (fluxloading-1.1.3-49.jar)
                                        
                                      NothiriumPlugin (Nothirium-1.12.2-0.4.2-beta.jar)
                                        
                                      BTFixesCore (BTFixes-1.12.2-1.2.2.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      Snow! Real Magic! (SnowRealMagic-1.12.2-0.7.4.jar)
                                        
                                      MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
                                        ichttt.mods.moresoundconfig.asm.MSCTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
                                        bre.smoothfont.asm.Transformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      FarseekCoreMod (Farseek-1.12-2.5.1.jar)
                                        farseek.core.FarseekClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
                                        
                                      Fluidlogged API Plugin (Fluidlogged-API-v2.2.7-mc1.12.2.jar)
                                        git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
                                        git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerLevelProperty
                                        git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerSmoothWater
                                      ASMPlugin (justenoughmagiculture-1.12.2-1.2.1.jar)
                                        com.invadermonky.justenoughmagiculture.asm.ASMTransformer
                                      VintageFix (vintagefix-0.5.5.jar)
                                        org.embeddedt.vintagefix.transformer.ASMModParserTransformer
                                      MixinBooter (!mixinbooter-10.5.jar)
                                        
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      CTALoadingPlugin (cta-1.12.2-1.2.2.jar)
                                        
                                      ConfigAnytimePlugin (!configanytime-3.0.jar)
                                        
                                      serializationisbad (serializationisbad-1.5.2.jar)
                                        io.dogboy.serializationisbad.legacyforge.SIBTransformer
                                      EntityCullingPlugin (EntityCulling-1.12.2-6.5.0.jar)
                                        
                                      NyxCore (Nyx-Hexxit-II-1.5.0-116.jar)
                                        
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.14.1-778.jar)
                                        
                                      DLFMLCorePlugin (DynamicLights-1.12.2.jar)
                                        atomicstryker.dynamiclights.common.DLTransformer
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge-14.23.5.2860
  LWJGL: 2.9.4
  OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  GL Caps: 
  Using VBOs: ~~ERROR~~ NullPointerException: null
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: ~~ERROR~~ NullPointerException: null
  Current Language: ~~ERROR~~ NullPointerException: null
  Profiler Position: N/A (disabled)
  CPU: <unknown>

**Comment by xJon** [comment]
@n18rt Make sure you are using the latest version and report the crash directly to them. Not sure how I can help beyond that, sorry!

**Comment by ACGaming** [comment]
Essential is incompatible with MixinBooter and thus can't be used with the pack currently.

**Comment by ACGaming** [comment]
Apparently there's the Java argument `-Dessential.loader.relaunch=false` to fix this issue, you could give it a try!

![Image](https://github.com/user-attachments/assets/3d0b6f9e-2370-4344-93bb-15a23733fe6e)

**Comment by xJon** [comment]
Closing due to inactivity.
